# Generated by Django 4.2.2 on 2023-06-20 22:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='wanters',
            field=models.ManyToManyField(related_name='wanters_article_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movie',
            name='watchers',
            field=models.ManyToManyField(related_name='watchers_article_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
