# Generated by Django 4.2.2 on 2023-06-21 00:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0002_movie_wanters_movie_watchers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='wanters',
            field=models.ManyToManyField(related_name='wanters_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movie',
            name='watchers',
            field=models.ManyToManyField(related_name='watchers_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
