# Generated by Django 4.2.2 on 2023-06-22 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='opinion',
            new_name='movie',
        ),
    ]
